#!/usr/bin/env bash
# mm-commands.sh - MM command implementations
# This file contains all MM command implementations

#-------------------------------------------------------------------------------
# Interactive Configuration Generator
#-------------------------------------------------------------------------------

# Initialize project configuration
mm::cmd_init() {
    local project_dir="${1:-$(pwd)}"
    local project_name

    # Normalize project directory
    project_dir="$(cd "$project_dir" 2>/dev/null && pwd)" || {
        mm::error "Invalid directory: $project_dir"
        exit 1
    }

    project_name="$(basename "$project_dir")"

    mm::info "Initializing mm for project: $project_name"
    mm::info "Project directory: $project_dir"
    echo ""

    # Check if config already exists
    if [[ -f "$MM_CONFIG_FILE" ]]; then
        mm::warn "Configuration file already exists: $MM_CONFIG_FILE"
        read -p "Overwrite? [y/N] " -n 1 -r
        echo ""
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            mm::info "Cancelled"
            exit 0
        fi
    fi

    # Detect project type
    mm::info "Detecting project type..."
    local project_type="generic"

    if [[ -f "$project_dir/package.json" ]]; then
        project_type="nodejs"
        mm::info "  -> Detected Node.js project (package.json found)"
    elif [[ -f "$project_dir/Assets" ]] || grep -q "Unity" "$project_dir/"*.sln 2>/dev/null; then
        project_type="unity-csharp"
        mm::info "  -> Detected Unity C# project"
    elif [[ -f "$project_dir/pyproject.toml" ]] || [[ -f "$project_dir/setup.py" ]] || [[ -f "$project_dir/requirements.txt" ]]; then
        project_type="python"
        mm::info "  -> Detected Python project"
    else
        mm::info "  -> Using generic project type"
    fi

    echo ""
    read -p "Project type [$project_type]: " -r input
    if [[ -n "$input" ]]; then
        project_type="$input"
    fi

    # Generate configuration
    mm::info "Generating configuration file..."

    cat > "$MM_CONFIG_FILE" <<EOF
# $project_name - mm configuration
# Generated by ai-dev-workstation

# Project Configuration
PROJECT_NAME="$project_name"
PROJECT_DIR="$project_dir"
PROJECT_WIN="$(mm::wsl_to_win "$project_dir")"
PROJECT_TYPE="$project_type"

# Windows Drive Mounts
WINDOWS_DRIVE_F="/mnt/f"
WINDOWS_DRIVE_C="/mnt/c"

# Application Paths (Windows format)
declare -A APPS
APPS[code]="C:\\Program Files\\Microsoft VS Code\\Code.exe"
APPS[vs]="C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe"
APPS[rider]="C:\\Users\\$(whoami | sed 's/.*/\L&/')\\AppData\\Local\\Programs\\Rider\\bin\\rider64.exe"
APPS[unity]="C:\\Program Files\\Unity Hub\\Unity Hub.exe"

# Zellij Configuration
ZELLIJ_LAYOUT="ai_workstation"

# Custom Commands
declare -A CMDS
EOF

    # Add project-type specific commands
    case "$project_type" in
        nodejs)
            cat >> "$MM_CONFIG_FILE" <<'EOF'
CMDS[install]="npm install"
CMDS[dev]="npm run dev"
CMDS[build]="npm run build"
CMDS[test]="npm test"
CMDS[lint]="npm run lint"
EOF
            ;;
        python)
            cat >> "$MM_CONFIG_FILE" <<'EOF'
CMDS[install]="pip install -e ."
CMDS[dev]="python -m dev"
CMDS[test]="pytest"
CMDS[lint]="ruff check ."
CMDS[format]="ruff format ."
EOF
            ;;
        unity-csharp)
            cat >> "$MM_CONFIG_FILE" <<'EOF'
CMDS[build]="dotnet build Src/Server/GameServer/GameServer.sln"
CMDS[run]="dotnet run --project Src/Server/GameServer/GameServer"
CMDS[test]="dotnet test"
CMDS[proto]="bash Tools/genproto.sh"
CMDS[data]="bash Src/Data/Excel2Json.sh"
EOF
            ;;
        *)
            cat >> "$MM_CONFIG_FILE" <<'EOF'
CMDS[build]="echo 'Configure build command in .mmrc'"
CMDS[test]="echo 'Configure test command in .mmrc'"
CMDS[run]="echo 'Configure run command in .mmrc'"
EOF
            ;;
    esac

    cat >> "$MM_CONFIG_FILE" <<'EOF'

# Workspace Applications (launched by 'mm' or 'mm workspace')
WORKSPACE_APPS=("code")
EOF

    mm::success "Configuration created: $MM_CONFIG_FILE"
    echo ""
    mm::info "Next steps:"
    echo "  1. Review and edit $MM_CONFIG_FILE"
    echo "  2. Run: mm ai          # Start AI workstation"
    echo "  3. Run: mm             # Start full workspace"
}

#-------------------------------------------------------------------------------
# Workspace Commands
#-------------------------------------------------------------------------------

# Start AI workstation only
mm::cmd_ai() {
    mm::load_config
    mm::validate_config

    if ! mm::check_command zellij "zellij"; then
        exit 1
    fi

    mm::cd_project
    mm::info "Starting AI workstation with layout: $ZELLIJ_LAYOUT"
    zellij --layout "$ZELLIJ_LAYOUT" --session "${PROJECT_NAME}-ai"
}

# Start full workspace (IDEs + AI)
mm::cmd_workspace() {
    mm::load_config
    mm::validate_config
    mm::check_wsl

    mm::info "Launching workspace applications..."

    # Launch workspace apps
    for app in "${WORKSPACE_APPS[@]:-}"; do
        local app_path="${APPS[$app]:-}"
        if [[ -n "$app_path" ]]; then
            mm::info "  Launching $app..."
            cmd.exe /c start "" "$app_path" "$PROJECT_WIN" 2>/dev/null || true
        fi
    done

    # Start AI workstation
    mm::cmd_ai
}

# Stop workspace applications
mm::cmd_stop() {
    mm::load_config

    echo "即将关闭以下工具："
    for app in "${WORKSPACE_APPS[@]:-}"; do
        local app_path="${APPS[$app]:-}"
        if [[ -n "$app_path" ]]; then
            echo "  - $app"
        fi
    done
    echo "  - Zellij 工作站"
    echo "  - WezTerm 窗口"
    echo ""
    read -p "确认关闭？[y/N] " -n 1 -r
    echo ""

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        mm::info "正在关闭工具..."

        # Close Windows applications
        for app in "${WORKSPACE_APPS[@]:-}"; do
            local app_path="${APPS[$app]:-}"
            if [[ -n "$app_path" ]]; then
                local exe_name
                exe_name="$(basename "$app_path" .exe)"
                taskkill.exe /IM "${exe_name}.exe" /F 2>/dev/null | iconv -f GBK -t UTF-8 2>/dev/null || true
            fi
        done

        # Exit zellij
        if [[ "$ZELLIJ" = "1" ]]; then
            mm::info "退出 Zellij..."
            exit
        else
            mm::info "未在 Zellij 中运行"
        fi
    else
        mm::info "已取消"
    fi
}

#-------------------------------------------------------------------------------
# Custom Command Execution
#-------------------------------------------------------------------------------

# Execute custom command
mm::cmd_exec() {
    if [[ $# -eq 0 ]]; then
        mm::error "Usage: mm exec <command> [args...]"
        mm::info "Available commands:"
        mm::load_config
        for cmd in "${!CMDS[@]}"; do
            echo "  - $cmd: ${CMDS[$cmd]}"
        done
        exit 1
    fi

    local cmd_name="$1"
    shift

    mm::load_config
    mm::validate_config

    if [[ -z "${CMDS[$cmd_name]:-}" ]]; then
        mm::error "Unknown command: $cmd_name"
        mm::info "Available commands: ${!CMDS[*]}"
        exit 1
    fi

    mm::cd_project
    mm::info "Executing: $cmd_name"
    eval "${CMDS[$cmd_name]} $*"
}

# List available commands
mm::cmd_list() {
    mm::load_config

    echo "Project: $PROJECT_NAME"
    echo "Directory: $PROJECT_DIR"
    echo "Type: $PROJECT_TYPE"
    echo ""
    echo "Available commands:"
    for cmd in "${!CMDS[@]}"; do
        printf "  %-12s %s\n" "$cmd" "${CMDS[$cmd]}"
    done
    echo ""
    echo "Workspace apps: ${WORKSPACE_APPS[*]:-none}"
}

#-------------------------------------------------------------------------------
# Help Command
#-------------------------------------------------------------------------------

# Show help information
mm::cmd_help() {
    cat <<'EOF'
mm - AI Dev Workstation Project Manager

USAGE:
    mm [command] [args]

COMMANDS:
    mm init [dir]       Initialize project configuration
    mm                  Start full workspace (apps + AI)
    mm ai               Start AI workstation only
    mm stop             Stop workspace applications
    mm exec <cmd>       Execute custom command
    mm list             List available commands
    mm help             Show this help message
    mm version          Show version information

CONFIGURATION:
    Configuration file: ~/.mmrc
    Edit this file to customize your project settings.

FOR MORE INFORMATION:
    https://github.com/ai-dev-workstation/ai-dev-workstation
EOF
}
